### ISSUE TITLE
nb.to_inference() error

### ISSUE THREAD

**Issue by akhilkommala** [biocore/BIRDMAn#98]
I was going through the default Negative Binomial model tutorial in the BIRDMAn documentation, but my code produces the following error when I run the line nb.to_inference():
![image](https://github.com/biocore/BIRDMAn/assets/87740618/38c4bb2c-e032-4259-be4c-ac139ea6b181)
I wanted to see if anyone knew of a solution to this issue or of what may be going wrong.
Thanks!

**Comment by gibsramen** [comment]
Hi, @akhilkommala 

Can you report what version of the following you are using?

* BIRDMAn
* CmdStanPy
* CmdStan
* Python

BIRDMAn has had some substantial updates recently along with updates to the underlying CmdStanPy dependency and we're still trying to work out some of the bugs.

Thanks!

**Comment by gibsramen** [comment]
Can you try updating to BIRDMAn version 0.2.0?

**Comment by gibsramen** [comment]
Okay, thanks. Which tutorial were you following when you received this error? In the meantime you can try [this](https://colab.research.google.com/drive/1zT4eIgiz0Jl5TVmttE3gwWnrhNlPeYDc?usp=sharing) Colab notebook which should go through installation and usage. I am travelling at the moment so my responses may be slow, apologies.

**Comment by akhilkommala** [comment]
Thanks, I'll take a look at that. I was running through this tutorial on the birdman documentation: https://birdman.readthedocs.io/en/stable/default_model_example.html
